server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Don't auto-launch the browser; we run the dev server headless.
vaadin.launch-browser=false

# Restrict component scanning for faster dev startup.
# https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.sujoy.calculators
